// 插件控制面协议（v1）。
//
// 协议双方：插件进程实现本服务的全部 RPC（作为 gRPC server 监听本机回环端口），
// PortalT 作为 gRPC client 主动连接。gRPC 与 HTTP 两个回环端口均由 PortalT 分配
// 并经环境变量 PORTALT_PLUGIN_GRPC_PORT / PORTALT_PLUGIN_HTTP_PORT 下发，
// 插件绑定后经 Handshake 单向确认（无需自行上报端口）；数据面走插件自起的
// HTTP 服务（监听下发的 HTTP 端口），PortalT 反代暴露。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginControl_Handshake_FullMethodName = "/plugin.v1.PluginControl/Handshake"
	PluginControl_Health_FullMethodName    = "/plugin.v1.PluginControl/Health"
	PluginControl_Shutdown_FullMethodName  = "/plugin.v1.PluginControl/Shutdown"
	PluginControl_Notify_FullMethodName    = "/plugin.v1.PluginControl/Notify"
)

// PluginControlClient is the client API for PluginControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginControl 插件进程实现的控制面服务。
type PluginControlClient interface {
	// Handshake 启动握手：PortalT 下发 manifest 与端口信息，插件确认并返回启用状态。
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Health 健康探测：PortalT 周期调用（间隔取 manifest 声明），
	// 判断插件进程是否存活并就绪。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Shutdown 优雅停机：禁用 / 升级 / 删除插件时由 PortalT 调用。
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// Notify 事件通知：enabled / disabled / config_changed 等钩子回调。
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
}

type pluginControlClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginControlClient(cc grpc.ClientConnInterface) PluginControlClient {
	return &pluginControlClient{cc}
}

func (c *pluginControlClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, PluginControl_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginControl_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, PluginControl_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginControlClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, PluginControl_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginControlServer is the server API for PluginControl service.
// All implementations must embed UnimplementedPluginControlServer
// for forward compatibility.
//
// PluginControl 插件进程实现的控制面服务。
type PluginControlServer interface {
	// Handshake 启动握手：PortalT 下发 manifest 与端口信息，插件确认并返回启用状态。
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Health 健康探测：PortalT 周期调用（间隔取 manifest 声明），
	// 判断插件进程是否存活并就绪。
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Shutdown 优雅停机：禁用 / 升级 / 删除插件时由 PortalT 调用。
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// Notify 事件通知：enabled / disabled / config_changed 等钩子回调。
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	mustEmbedUnimplementedPluginControlServer()
}

// UnimplementedPluginControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginControlServer struct{}

func (UnimplementedPluginControlServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedPluginControlServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginControlServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginControlServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedPluginControlServer) mustEmbedUnimplementedPluginControlServer() {}
func (UnimplementedPluginControlServer) testEmbeddedByValue()                       {}

// UnsafePluginControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginControlServer will
// result in compilation errors.
type UnsafePluginControlServer interface {
	mustEmbedUnimplementedPluginControlServer()
}

func RegisterPluginControlServer(s grpc.ServiceRegistrar, srv PluginControlServer) {
	// If the following call panics, it indicates UnimplementedPluginControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginControl_ServiceDesc, srv)
}

func _PluginControl_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginControl_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginControlServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginControl_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginControlServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginControl_ServiceDesc is the grpc.ServiceDesc for PluginControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginControl",
	HandlerType: (*PluginControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _PluginControl_Handshake_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginControl_Health_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PluginControl_Shutdown_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _PluginControl_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/v1/plugin.proto",
}
