// 插件控制面协议（v1）。
//
// 协议双方：插件进程实现本服务的全部 RPC（作为 gRPC server 监听本机回环端口），
// PortalT 作为 gRPC client 主动连接。gRPC 与 HTTP 两个回环端口均由 PortalT 分配
// 并经环境变量 PORTALT_PLUGIN_GRPC_PORT / PORTALT_PLUGIN_HTTP_PORT 下发，
// 插件绑定后经 Handshake 单向确认（无需自行上报端口）；数据面走插件自起的
// HTTP 服务（监听下发的 HTTP 端口），PortalT 反代暴露。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotifyEvent 事件类型。
type NotifyEvent int32

const (
	// NOTIFY_EVENT_UNSPECIFIED 未指定（不应使用）。
	NotifyEvent_NOTIFY_EVENT_UNSPECIFIED NotifyEvent = 0
	// ENABLED 插件被启用。
	NotifyEvent_ENABLED NotifyEvent = 1
	// DISABLED 插件被停用。
	NotifyEvent_DISABLED NotifyEvent = 2
	// CONFIG_CHANGED 插件配置变更（权限 / 排序等）。
	NotifyEvent_CONFIG_CHANGED NotifyEvent = 3
	// RESTARTING 插件即将重启（升级场景）。
	NotifyEvent_RESTARTING NotifyEvent = 4
)

// Enum value maps for NotifyEvent.
var (
	NotifyEvent_name = map[int32]string{
		0: "NOTIFY_EVENT_UNSPECIFIED",
		1: "ENABLED",
		2: "DISABLED",
		3: "CONFIG_CHANGED",
		4: "RESTARTING",
	}
	NotifyEvent_value = map[string]int32{
		"NOTIFY_EVENT_UNSPECIFIED": 0,
		"ENABLED":                  1,
		"DISABLED":                 2,
		"CONFIG_CHANGED":           3,
		"RESTARTING":               4,
	}
)

func (x NotifyEvent) Enum() *NotifyEvent {
	p := new(NotifyEvent)
	*p = x
	return p
}

func (x NotifyEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (NotifyEvent) Type() protoreflect.EnumType {
	return &file_proto_plugin_v1_plugin_proto_enumTypes[0]
}

func (x NotifyEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyEvent.Descriptor instead.
func (NotifyEvent) EnumDescriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Manifest 插件元信息（与 manifest.json 字段一致，用于一致性校验）。
type Manifest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                  string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Route                 string                 `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	SortOrder             int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Permission            string                 `protobuf:"bytes,6,opt,name=permission,proto3" json:"permission,omitempty"`
	HealthIntervalSeconds int32                  `protobuf:"varint,7,opt,name=health_interval_seconds,json=healthIntervalSeconds,proto3" json:"health_interval_seconds,omitempty"`
	// version 插件版本号（如 "1.2.0"），供管理界面展示与兼容性判断。
	Version string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// description 插件一句话描述，供管理界面展示。
	Description   string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Manifest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Manifest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Manifest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Manifest) GetHealthIntervalSeconds() int32 {
	if x != nil {
		return x.HealthIntervalSeconds
	}
	return 0
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// HandshakeRequest 握手请求。
type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manifest PortalT 下发的插件元信息（与 plugins 表 / manifest.json 一致）。
	Manifest *Manifest `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// http_port PortalT 分配的插件 HTTP 数据面端口（回环地址 127.0.0.1）。
	HttpPort      int32 `protobuf:"varint,2,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *HandshakeRequest) GetHttpPort() int32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

// HandshakeResponse 握手响应。
type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled PortalT 决定插件当前是否处于启用状态。
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// reason 拒绝或启用的说明（如插件未注册、manifest 不一致）。
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// portal_version PortalT 版本号，供插件做兼容性判断。
	PortalVersion string `protobuf:"bytes,3,opt,name=portal_version,json=portalVersion,proto3" json:"portal_version,omitempty"`
	// config 下发给插件的键值配置（未来扩展，如授权端点开关）。
	Config        map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *HandshakeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandshakeResponse) GetPortalVersion() string {
	if x != nil {
		return x.PortalVersion
	}
	return ""
}

func (x *HandshakeResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// HealthRequest 健康探测请求（无参数）。
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

// HealthResponse 健康探测响应。
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ShutdownRequest 停机请求。
type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reason 停机原因（disable / upgrade / delete）。
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ShutdownResponse 停机响应。
type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

// NotifyRequest 事件通知请求。
type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         NotifyEvent            `protobuf:"varint,1,opt,name=event,proto3,enum=plugin.v1.NotifyEvent" json:"event,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyRequest) GetEvent() NotifyEvent {
	if x != nil {
		return x.Event
	}
	return NotifyEvent_NOTIFY_EVENT_UNSPECIFIED
}

func (x *NotifyRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// NotifyResponse 事件通知响应。
type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\tplugin.v1\"\x8b\x02\n" +
	"\bManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05route\x18\x04 \x01(\tR\x05route\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12\x1e\n" +
	"\n" +
	"permission\x18\x06 \x01(\tR\n" +
	"permission\x126\n" +
	"\x17health_interval_seconds\x18\a \x01(\x05R\x15healthIntervalSeconds\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"`\n" +
	"\x10HandshakeRequest\x12/\n" +
	"\bmanifest\x18\x01 \x01(\v2\x13.plugin.v1.ManifestR\bmanifest\x12\x1b\n" +
	"\thttp_port\x18\x02 \x01(\x05R\bhttpPort\"\xe9\x01\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0eportal_version\x18\x03 \x01(\tR\rportalVersion\x12@\n" +
	"\x06config\x18\x04 \x03(\v2(.plugin.v1.HandshakeResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\")\n" +
	"\x0fShutdownRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x12\n" +
	"\x10ShutdownResponse\"\xae\x01\n" +
	"\rNotifyRequest\x12,\n" +
	"\x05event\x18\x01 \x01(\x0e2\x16.plugin.v1.NotifyEventR\x05event\x126\n" +
	"\x04data\x18\x02 \x03(\v2\".plugin.v1.NotifyRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eNotifyResponse*j\n" +
	"\vNotifyEvent\x12\x1c\n" +
	"\x18NOTIFY_EVENT_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02\x12\x12\n" +
	"\x0eCONFIG_CHANGED\x10\x03\x12\x0e\n" +
	"\n" +
	"RESTARTING\x10\x042\x9a\x02\n" +
	"\rPluginControl\x12F\n" +
	"\tHandshake\x12\x1b.plugin.v1.HandshakeRequest\x1a\x1c.plugin.v1.HandshakeResponse\x12=\n" +
	"\x06Health\x12\x18.plugin.v1.HealthRequest\x1a\x19.plugin.v1.HealthResponse\x12C\n" +
	"\bShutdown\x12\x1a.plugin.v1.ShutdownRequest\x1a\x1b.plugin.v1.ShutdownResponse\x12=\n" +
	"\x06Notify\x12\x18.plugin.v1.NotifyRequest\x1a\x19.plugin.v1.NotifyResponseB\"Z portalt/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(NotifyEvent)(0),          // 0: plugin.v1.NotifyEvent
	(*Manifest)(nil),          // 1: plugin.v1.Manifest
	(*HandshakeRequest)(nil),  // 2: plugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 3: plugin.v1.HandshakeResponse
	(*HealthRequest)(nil),     // 4: plugin.v1.HealthRequest
	(*HealthResponse)(nil),    // 5: plugin.v1.HealthResponse
	(*ShutdownRequest)(nil),   // 6: plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),  // 7: plugin.v1.ShutdownResponse
	(*NotifyRequest)(nil),     // 8: plugin.v1.NotifyRequest
	(*NotifyResponse)(nil),    // 9: plugin.v1.NotifyResponse
	nil,                       // 10: plugin.v1.HandshakeResponse.ConfigEntry
	nil,                       // 11: plugin.v1.NotifyRequest.DataEntry
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	1,  // 0: plugin.v1.HandshakeRequest.manifest:type_name -> plugin.v1.Manifest
	10, // 1: plugin.v1.HandshakeResponse.config:type_name -> plugin.v1.HandshakeResponse.ConfigEntry
	0,  // 2: plugin.v1.NotifyRequest.event:type_name -> plugin.v1.NotifyEvent
	11, // 3: plugin.v1.NotifyRequest.data:type_name -> plugin.v1.NotifyRequest.DataEntry
	2,  // 4: plugin.v1.PluginControl.Handshake:input_type -> plugin.v1.HandshakeRequest
	4,  // 5: plugin.v1.PluginControl.Health:input_type -> plugin.v1.HealthRequest
	6,  // 6: plugin.v1.PluginControl.Shutdown:input_type -> plugin.v1.ShutdownRequest
	8,  // 7: plugin.v1.PluginControl.Notify:input_type -> plugin.v1.NotifyRequest
	3,  // 8: plugin.v1.PluginControl.Handshake:output_type -> plugin.v1.HandshakeResponse
	5,  // 9: plugin.v1.PluginControl.Health:output_type -> plugin.v1.HealthResponse
	7,  // 10: plugin.v1.PluginControl.Shutdown:output_type -> plugin.v1.ShutdownResponse
	9,  // 11: plugin.v1.PluginControl.Notify:output_type -> plugin.v1.NotifyResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_proto_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
